[2025-08-06T01:37:59.286+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.load_customer_transactions_raw scheduled__2025-08-05T00:00:00+00:00 [queued]>
[2025-08-06T01:37:59.292+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.load_customer_transactions_raw scheduled__2025-08-05T00:00:00+00:00 [queued]>
[2025-08-06T01:37:59.293+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-06T01:37:59.305+0000] {taskinstance.py:2214} INFO - Executing <Task(AirbyteTriggerSyncOperator): load_customer_transactions_raw> on 2025-08-05 00:00:00+00:00
[2025-08-06T01:37:59.312+0000] {standard_task_runner.py:60} INFO - Started process 5554 to run task
[2025-08-06T01:37:59.314+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'load_customer_transactions_raw', 'scheduled__2025-08-05T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmp07gjm_un']
[2025-08-06T01:37:59.316+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask load_customer_transactions_raw
[2025-08-06T01:37:59.365+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.load_customer_transactions_raw scheduled__2025-08-05T00:00:00+00:00 [running]> on host a4babef49899
[2025-08-06T01:37:59.450+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='load_customer_transactions_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-05T00:00:00+00:00'
[2025-08-06T01:37:59.460+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:38:02.608+0000] {airbyte.py:86} INFO - Job 7 was submitted to Airbyte Server
[2025-08-06T01:38:02.608+0000] {airbyte.py:88} INFO - Waiting for job 7 to complete
[2025-08-06T01:38:05.635+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:38:11.887+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:38:39.107+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:05.159+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:08.499+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:11.532+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:14.554+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:17.576+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:20.605+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:23.633+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:26.658+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:29.686+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:32.771+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:35.927+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:38.951+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:41.977+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:45.000+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:48.029+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:51.087+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:39:51.116+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 111, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 141, in wait_for_job
    raise Exception(f"Encountered unexpected state `{state}` for job_id `{job_id}`")
Exception: Encountered unexpected state `failed` for job_id `7`
[2025-08-06T01:39:51.148+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=load_customer_transactions_raw, execution_date=20250805T000000, start_date=20250806T013759, end_date=20250806T013951
[2025-08-06T01:39:51.187+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task load_customer_transactions_raw (Encountered unexpected state `failed` for job_id `7`; 5554)
[2025-08-06T01:39:51.233+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T01:39:51.358+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
