[2025-08-06T02:02:18.095+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: customer_metrics.publish.labeled_transactions_run manual__2025-08-06T02:01:22.902312+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
