[2025-08-06T01:50:17.201+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_transactions_run manual__2025-08-06T01:50:02.784766+00:00 [queued]>
[2025-08-06T01:50:17.422+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_transactions_run manual__2025-08-06T01:50:02.784766+00:00 [queued]>
[2025-08-06T01:50:17.423+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-06T01:50:17.445+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_transactions_run> on 2025-08-06 01:50:02.784766+00:00
[2025-08-06T01:50:17.457+0000] {standard_task_runner.py:60} INFO - Started process 6501 to run task
[2025-08-06T01:50:17.463+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_transactions_run', 'manual__2025-08-06T01:50:02.784766+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpz48ebdcr']
[2025-08-06T01:50:17.466+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask publish.customer_transactions_run
[2025-08-06T01:50:17.550+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_transactions_run manual__2025-08-06T01:50:02.784766+00:00 [running]> on host a4babef49899
[2025-08-06T01:50:17.682+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_transactions_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T01:50:02.784766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T01:50:02.784766+00:00'
[2025-08-06T01:50:17.684+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmpvllytn1s from /opt/airflow/include/dbt/fraud
[2025-08-06T01:50:17.685+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2025-08-06T01:50:17.685+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_transactions', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmpvllytn1s
[2025-08-06T01:50:17.686+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2025-08-06T01:50:17.686+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2025-08-06T01:50:17.687+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_transactions', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2025-08-06T01:50:17.703+0000] {subprocess.py:84} INFO - Command output:
[2025-08-06T01:50:22.626+0000] {subprocess.py:94} INFO - [0m01:50:22  Running with dbt=1.8.7
[2025-08-06T01:50:55.684+0000] {subprocess.py:94} INFO - [0m01:50:55  Registered adapter: snowflake=1.8.4
[2025-08-06T01:50:55.764+0000] {subprocess.py:94} INFO - [0m01:50:55  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-08-06T01:50:58.602+0000] {subprocess.py:94} INFO - [0m01:50:58  Found 3 models, 454 macros
[2025-08-06T01:50:58.603+0000] {subprocess.py:94} INFO - [0m01:50:58
[2025-08-06T01:50:59.849+0000] {subprocess.py:94} INFO - [0m01:50:59
[2025-08-06T01:50:59.850+0000] {subprocess.py:94} INFO - [0m01:50:59  Finished running  in 0 hours 0 minutes and 1.25 seconds (1.25s).
[2025-08-06T01:50:59.851+0000] {subprocess.py:94} INFO - [0m01:50:59  Encountered an error:
[2025-08-06T01:50:59.851+0000] {subprocess.py:94} INFO - Runtime Error
[2025-08-06T01:50:59.852+0000] {subprocess.py:94} INFO -   Database error while listing schemas in database "AIRBYTE_DATABASE"
[2025-08-06T01:50:59.852+0000] {subprocess.py:94} INFO -   Database Error
[2025-08-06T01:50:59.853+0000] {subprocess.py:94} INFO -     250001 (08001): Failed to connect to DB: cp91742.eu-west-3.aws.snowflakecomputing.com:443. Incorrect username or password was specified.
[2025-08-06T01:51:01.959+0000] {subprocess.py:98} INFO - Command exited with return code 2
[2025-08-06T01:51:01.974+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2025-08-06T01:51:01.975+0000] {local.py:252} INFO - Inlets: []
[2025-08-06T01:51:01.975+0000] {local.py:253} INFO - Outlets: []
[2025-08-06T01:51:01.976+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2025-08-06T01:51:02.037+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2025-08-06 00:00:00+00:00, run_after=2025-08-07 00:00:00+00:00
[2025-08-06T01:51:02.078+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m01:50:22  Running with dbt=1.8.7', '\x1b[0m01:50:55  Registered adapter: snowflake=1.8.4', '\x1b[0m01:50:55  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m01:50:58  Found 3 models, 454 macros', '\x1b[0m01:50:58', '\x1b[0m01:50:59', '\x1b[0m01:50:59  Finished running  in 0 hours 0 minutes and 1.25 seconds (1.25s).', '\x1b[0m01:50:59  Encountered an error:', 'Runtime Error', '  Database error while listing schemas in database "AIRBYTE_DATABASE"', '  Database Error', '    250001 (08001): Failed to connect to DB: cp91742.eu-west-3.aws.snowflakecomputing.com:443. Incorrect username or password was specified.')
[2025-08-06T01:51:02.081+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_transactions_run, execution_date=20250806T015002, start_date=20250806T015017, end_date=20250806T015102
[2025-08-06T01:51:02.097+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task publish.customer_transactions_run (('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m01:50:22  Running with dbt=1.8.7', '\x1b[0m01:50:55  Registered adapter: snowflake=1.8.4', '\x1b[0m01:50:55  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m01:50:58  Found 3 models, 454 macros', '\x1b[0m01:50:58', '\x1b[0m01:50:59', '\x1b[0m01:50:59  Finished running  in 0 hours 0 minutes and 1.25 seconds (1.25s).', '\x1b[0m01:50:59  Encountered an error:', 'Runtime Error', '  Database error while listing schemas in database "AIRBYTE_DATABASE"', '  Database Error', '    250001 (08001): Failed to connect to DB: cp91742.eu-west-3.aws.snowflakecomputing.com:443. Incorrect username or password was specified.'); 6501)
[2025-08-06T01:51:02.111+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T01:51:02.159+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
