[2025-08-20T23:15:54.050+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.audit_customer_transactions manual__2025-08-20T23:14:29.235873+00:00 [queued]>
[2025-08-20T23:15:54.187+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.audit_customer_transactions manual__2025-08-20T23:14:29.235873+00:00 [queued]>
[2025-08-20T23:15:54.187+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-20T23:15:54.199+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): audit_customer_transactions> on 2025-08-20 23:14:29.235873+00:00
[2025-08-20T23:15:54.205+0000] {standard_task_runner.py:60} INFO - Started process 10496 to run task
[2025-08-20T23:15:54.208+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_pipeline', 'audit_customer_transactions', 'manual__2025-08-20T23:14:29.235873+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp_ego1c76']
[2025-08-20T23:15:54.209+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask audit_customer_transactions
[2025-08-20T23:15:54.258+0000] {task_command.py:423} INFO - Running <TaskInstance: fraud_detection_pipeline.audit_customer_transactions manual__2025-08-20T23:14:29.235873+00:00 [running]> on host f3fd0a28023e
[2025-08-20T23:15:54.342+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='audit_customer_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T23:14:29.235873+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T23:14:29.235873+00:00'
[2025-08-20T23:15:54.343+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T23:15:54.344+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d staging -c include/soda/configuration.yml include/soda/checks/tables/customer_transaction.yml']
[2025-08-20T23:15:54.358+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T23:15:54.362+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: soda: command not found
[2025-08-20T23:15:54.363+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-20T23:15:54.377+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-20T23:15:54.380+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=audit_customer_transactions, execution_date=20250820T231429, start_date=20250820T231554, end_date=20250820T231554
[2025-08-20T23:15:54.394+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task audit_customer_transactions (Bash command failed. The command returned a non-zero exit code 127.; 10496)
[2025-08-20T23:15:54.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-20T23:15:54.519+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
